blank_issues_enabled: false
contact_links:
  - name: 🔒 Security Vulnerability
    url: https://github.com/CrowdStrike/falcon-mcp/tree/main/docs/SECURITY.md
    about: Report security vulnerabilities privately
