name: Manual E2E Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Test with pytest
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        pytest --run-e2e

    - name: Generate HTML report
      if: always()
      run: |
        python scripts/generate_e2e_report.py

    - name: Upload HTML report artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: e2e-test-report
        path: ./static_test_report.html
